#!/bin/bash

RED="\033[1;31m"
CYAN="\033[1;36m"
YELLOW="\033[1;33m"
DEFAULT="\033[0m"

CONFIG_FILE=/root/.config/rclone/rclone.conf
CONFIG_FILE_EXAMPLE=/root/.config/rclone/rclone.conf.example

DRIVE_SYNC_FOLDER=${DRIVE_SYNC_FOLDER}
TARGET_FOLDER=/var/target
REPEAT=${REPEAT}
DRIVE_NAME=${DRIVE_NAME}
SYNC_OPTIONS=${SYNC_OPTIONS}
BI_DIRECTIONAL_SYNC=${BI_DIRECTIONAL_SYNC}

if [ ! -f "$CONFIG_FILE" ]; then
  echo -e "${RED}Cannot find "${CONFIG_FILE}". A example configuration can be found in "${CONFIG_FILE_EXAMPLE}".${DEFAULT}"
  exit 1
fi

while true
do
  echo -e "${CYAN}$(date +%d-%m-%Y-%H:%M:%S) - Start google drive sync.${DEFAULT}"
  echo -e "${YELLOW}Sync files from drive to ${TARGET_FOLDER}.${DEFAULT}"
  rclone sync ${DRIVE_NAME}:${DRIVE_SYNC_FOLDER} ${TARGET_FOLDER} ${SYNC_OPTIONS} -v --fast-list
  
  echo -e "${CYAN}$(date +%d-%m-%Y-%H:%M:%S) - Finished google drive sync.${DEFAULT}"
  
  sleep ${REPEAT}
done
